# Generated by Django 2.0.8 on 2019-12-22 17:36

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191221_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='aptm',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock())], default=''),
        ),
    ]
