# Generated by Django 2.0.8 on 2019-12-23 03:24

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_forms_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.RichTextBlock(classname='full title')), ('image', wagtail.images.blocks.ImageChooserBlock())]),
        ),
    ]
