# Generated by Django 2.0.8 on 2019-12-26 05:50

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_button'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='section',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.RichTextBlock(classname='full')), ('image', wagtail.images.blocks.ImageChooserBlock())]),
        ),
    ]
