# Generated by Django 2.0.8 on 2019-12-26 20:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0009_auto_20191226_1548'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Forms',
            new_name='Upload',
        ),
    ]
