# Generated by Django 2.0.8 on 2019-12-27 18:44

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20191226_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxinfo',
            name='section',
        ),
        migrations.AlterField(
            model_name='taxinfo',
            name='body',
            field=wagtail.core.fields.StreamField([('icon', wagtail.images.blocks.ImageChooserBlock()), ('link', wagtail.core.blocks.RichTextBlock())]),
        ),
    ]
