# Generated by Django 2.0.8 on 2019-12-28 02:08

from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20191227_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxinfo',
            name='body',
            field=wagtail.core.fields.StreamField([('table', wagtail.contrib.table_block.blocks.TableBlock()), ('icon', wagtail.images.blocks.ImageChooserBlock()), ('link', wagtail.core.blocks.RichTextBlock())]),
        ),
    ]
