# Generated by Django 2.0.8 on 2019-12-28 06:06

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20191228_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxinfo',
            name='body',
            field=wagtail.core.fields.StreamField([('icon', wagtail.images.blocks.ImageChooserBlock()), ('link', wagtail.core.blocks.RichTextBlock())]),
        ),
    ]
