# Generated by Django 2.0.8 on 2019-12-28 06:17

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20191228_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxinfo',
            name='body',
            field=wagtail.core.fields.StreamField([('icon_link', wagtail.core.blocks.RichTextBlock())]),
        ),
    ]
