# Generated by Django 2.0.8 on 2019-12-29 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20191228_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxinfo',
            name='header',
        ),
    ]
