# Generated by Django 2.0.8 on 2019-12-30 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_taxinfo_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='section',
        ),
    ]
